name: ThreatFox IOC

on:
  push:
    paths:
      - '.github/workflows/main.yml'  # 워크플로 파일이 수정되면 실행
  schedule:
    - cron: '0 */6 * * *'  # 6시간마다 실행
  workflow_dispatch:  # 수동 실행 가능

permissions:
  contents: write

jobs:
  collect-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: 리포지토리 체크아웃
      uses: actions/checkout@v3

    - name: Python 환경 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 의존성 패키지 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ThreatFox IOC 데이터 수집 및 변환
      run: python threatfox-abuse-automation.py

    - name: 변경 사항 확인
      run: |
        git diff --quiet || echo "Changes detected"

    - name: 변경된 데이터 GitHub에 푸시
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/threatfox_abuse_feed.json
        git commit -m "자동 업데이트: ThreatFox IOC 데이터 갱신" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
